[variables]
NIXPACKS_BUILD_CONTEXT = "server"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = []

[start]
cmd = "cd server && npm start"
