[build]
builder = "DOCKERFILE"
dockerfilePath = "server-rust/Dockerfile"
watchPatterns = ["server-rust/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
